### ISSUE TITLE
Problem with putItem - TruncatingBigNumber can not be converted to an String

### ISSUE THREAD

**Issue by artukrap** [aws/aws-sdk-php-laravel#104] opened 2016-08-28 07:26 UTC
```
[2016-08-27 21:47:22] local.INFO: array (                                                     
  'answer_texts' =>                                                                           
  array (                                                                                     
    1 => 'No',                                                                                
    2 => 'Sometimes',                                                                         
    3 => 'Yes',                                                                               
  ),                                                                                          
  'type' => 'multichoice',                                                                    
  'n' => 3,                                                                                 
  'can-comment' => 0,                                                                       
  'description' => '',                                                                        
  'groups' =>                                                                                 
  array (                                                                                     
    0 =>                                                                                      
    array (                                                                                   
      'question_id' => 205720,                                                              
      'group_id' => 17406,                                                                  
      'properties' =>                                                                         
      array (                                                                                 
        'question_code' => 'PQ1',                                                             
        'schoolsurvey' => 'Gmail - August 27, 2016',                                          
        'group_id' => 17406,                                                                
        'class' => 'Test',                                                                    
      ),                                                                                      
      'results' =>                                                                            
      array (                                                                                 
        'comments' =>                                                                         
        array (                                                                               
        ),                                                                                    
        'positive_n' => 5,                                                                  
        'n_of_answers' => 6,                                                                
        'average' => 4.33,                                                                  
        'answers' =>                                                                          
        array (                                                                               
          1 =>                                                                                
          array (                                                                             
            'n' => 1,                                                                       
          ),                                                                                  
          2 =>                                                                                
          array (                                                                             
            'n' => 0,                                                                       
          ),                                                                                  
          3 =>                                                                                
          array (                                                                             
            'n' => 5,                                                                       
          ),                                                                                  
        ),                                                                                    
      ),                                                                                      
    ),                                                                                        
  ),                                                                                          
  'mid_is_best' => false,                                                                     
  'grading_type' => '0-100',                                                                  
  'text' => 'The teacher helps me to achieve more.',                                          
  'order_index' => 1,                                                                       
  'id' => 205679,                                                                           
)                                                                                             
[2016-08-27 21:47:23] local.ERROR: exception 'Aws\DynamoDb\Exception\DynamoDbException' with m
https://dynamodb.eu-west-1.amazonaws.com` resulted in a `400 Bad Request` response:           
{"__type":"com.amazon.coral.service#SerializationException","Message":"class com.amazon.coral.
 SerializationException (client): class com.amazon.coral.value.json.numbers.TruncatingBigNumbe
m.amazon.coral.value.json.numbers.TruncatingBigNumber can not be converted to an String"}'    
                                                                                              
GuzzleHttp\Exception\ClientException: Client error: `POST https://dynamodb.eu-west-1.amazonaws
{"__type":"com.amazon.coral.service#SerializationException","Message":"class com.amazon.coral.
 in /home/vagrant/edurio_api/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:107  
```

So I am trying insert data into DynamoDb and getting this exception. Could you provide a solution for this?

Packages what I am using (currently running on PHP7):
```
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "aws/aws-sdk-php-laravel": "~3.0"
    }
```

**Comment by cjyclaire** [comment] 2016-08-29 23:34
@artukrap Thanks for the information, it would be much helpful if you could provide a [wire log](http://docs.aws.amazon.com/aws-sdk-php/v3/guide/faq.html#how-can-i-see-what-data-is-sent-over-the-wire) for me to see where goes wrong. 
Also, could you provide a code snippet that might help to reproduce the error perhaps? I couldn't find the variable that causing the converting trouble from the error message that provided.

**Comment by cjyclaire** [comment] 2016-09-12 17:12
Closing due to ages, yet feel free to reopen if you have further question or comments :)

**Closed by cjyclaire** 2016-09-12 17:12 UTC
Labels: waiting-for-reply

**Comment by vgilevich** [comment] 2017-01-31 13:12
I had same issue with PHP library. And found answer here:
https://forums.aws.amazon.com/thread.jspa?threadID=85285

in short - looks like Aws\Sdk expecting all values as string.
For example item with numeric values should be like:
```
  [
        'id' => ['S' => "test"],
	'stringValue' => ['S' => "test string"],
        'IntegerValue' => ['N' => "111"],
	'floatValue' => ['N' => "4.44"],
        'booleanValue' => ['N' => "1"]
 ];
```
