### ISSUE TITLE
“Class log does not exist”

### ISSUE THREAD

**Issue by martinbean** [aws/aws-sdk-php-laravel#95] opened 2016-01-21 22:31 UTC
After installing this package in a Laravel 5.2.10 application, it throws the following error when trying to view the app in a browser or use Artisan on the command line:

> Fatal error: Uncaught ReflectionException: Class log does not exist in /home/vagrant/vod.yourfightsite.com/vendor/laravel/framework/src/Illuminate/Container/Container.php:738 Stack trace: #0 /home/vagrant/vod.yourfightsite.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(738): ReflectionClass->__construct('log') #1 /home/vagrant/vod.yourfightsite.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build('log', Array) #2 /home/vagrant/vod.yourfightsite.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('log', Array) #3 /home/vagrant/vod.yourfightsite.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(853): Illuminate\Foundation\Application->make('log') #4 /home/vagrant/vod.yourfightsite.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(808): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter)) #5 /home/vagrant/vod.yourfightsite.com/ve in /home/vagrant/vod.yourfightsite.com/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 738

All I’m doing to install is:

    $ composer require aws/aws-sdk-php-laravel

Which installs version 3.1.0 of the package.

**Comment by jeremeamia** [comment] 2016-01-21 22:36
I have a hard time believing this issue is caused by this package. You may need to explore this a little more to track down the root cause.

<img width="1256" alt="screen shot 2016-01-21 at 2 37 55 pm" src="https://cloud.githubusercontent.com/assets/107867/12496697/1b5386e4-c04c-11e5-917b-7887e7989219.png">

**Comment by martinbean** [comment] 2016-01-21 22:45
@jeremeamia It’s just cropped up after installing the package, and adding the service provider. If I comment out the service provider in my *config/app.php* file then the errors go away, so it’s definitely something either in this library, or the core AWS PHP SDK.

**Comment by jeskew** [comment] 2016-01-21 23:10
Just adding the service provider won't cause any SDK code to be executed, and, as @jeremeamia points out, there is no reference in this package to a 'log' class.

I was not able to reproduce this issue after creating a Laravel application, installing the package, and adding the service provider to the `providers` array in `config/app.php`. After doing so, I was able to view pages and run artisan commands without any issues. Maybe there was an issue with the line you commented out (no comma before the next item in the array, invalid characters, etc.)?

**Comment by GrahamCampbell** [comment] 2016-01-22 09:16
Yes, this is not a bug. That error message is actually happening because an exception is being thrown after laravel's error handler has been registered, but before laravel's setup the log container bindings.

You'll need to intercept the error in the exception handler to see the true exception.

**Comment by jeskew** [comment] 2016-01-26 18:01
Closing, as @GrahamCampbell's explanation provides enough guidance to track down the error you're seeing. Please feel free to reopen if you have any questions or concerns.

**Closed by jeskew** 2016-01-26 18:01 UTC

**Comment by gocanto** [comment] 2016-03-25 01:38
Hey guys, I am passing through this issue by no reason and I don't know what to do. Can you point me on some direction?
